version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - ./work:/var/www/html
    depends_on:
      - oracle
  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8301:80"
    depends_on:
      - web
  oracle:
    image: oracle-db:19.3.0
    container_name: oracle
    shm_size: 1g
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./oracle/oradata:/opt/oracle/oradata
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=passw0rd
      - ORACLE_CHARACTERSET=AL32UTF8
      - TZ=Asia/Tokyo